### ISSUE TITLE
vote only wallets have a "voted" number that drifts up

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#849]
I run multiple vote only wallets so that votes are being cast redundantly. When looking at getstakeinfo on each of the boxes, I find that all the numbers look correct except "voted" which appears to be drifting higher then what is shown on a new wallet that is restored from seed. One theory is that since the boxes are casting votes which might get rejected if another vote is mined first, that these votes are being tallied and not removed as they should.

**Comment by alexlyp** [comment]
Can you verify that the vote choices on all the machines are the same?

I saw the same issue a while back due to different votechoices (and thereby different votes) from the same voting only wallets.

The bug at the core of this issue will hopefully be fixed in the current stake manager work by jrick

**Comment by jrick** [comment]
@raedah that theory is correct, the code that tracks stake transactions doesn't keep the info up to date with the chain, so once a vote is recorded, it is never removed, and if it is missed then the numbers won't line up.

I'm working on a solution to this currently.

**Comment by raedah** [comment]
I am still seeing the balance drift off, just on vote only machines. I suspect this issue is the cause. Work around of using rescanwallet is successful.
